-- Hey! This is a tool to learn how LuaJIT
-- works under the hood.

-- The code you submit shows here.
awesome = 'foobar' .. 1;

-- Press [Edit] to open code editor.

-- Choose [Lua] / [Bytecode] / [Mixed] display mode.
-- This will display either a source code,
-- a generated bytecode, or both interleaved.
-- In Lua mode, click on a source code line to
-- reveal bytecode behind that particular line.

local sumEven = 0
for i = 2,10000 do
  if i % 2 == 0 then 
    sumEven = sumEven + i
  end
end

-- Left pane displays JIT-compiled traces.
-- Click or hover a trace to highlight participating
-- code lines / bytecode instructions.
-- To the right of each highlighted line / instruction
-- a numeric label is displayed, depicting execution order.
-- Traces entered from the interpreter are depicted with
-- double circles.

-- Right pane displays properties of the currently
-- selected trace or function prototype. Check out
-- dynamically generated machine code!

local function forEveryFunctionDefinedThereIsAPrototype()
  return 42
end

-- Enjoy! NZ
